window.CITTACICO_PRODUCTS = [
  {
    slug: "sera-coat",
    category: "fashion",
    collection: "Fashion",
    name: "Sera Coat",
    price: 4800,
    description: "Hand-tailored cashmere overcoat with gold-thread detailing.",
    material: "Cashmere and silk lining",
    tone: "Midnight ivory",
    details: "Cut for a relaxed drape with atelier-finished edges and a soft shoulder.",
    number: "01"
  },
  {
    slug: "notte-blazer",
    category: "fashion",
    collection: "Fashion",
    name: "Notte Blazer",
    price: 3200,
    description: "Midnight wool blazer with asymmetric lapels.",
    material: "Super 150s wool",
    tone: "Noir",
    details: "A sculpted evening blazer with clean tailoring and subtle shine.",
    number: "02"
  },
  {
    slug: "alba-dress",
    category: "fashion",
    collection: "Fashion",
    name: "Alba Dress",
    price: 3600,
    description: "Flowing silk evening gown with draped bodice.",
    material: "Double silk charmeuse",
    tone: "Pearl",
    details: "Bias-cut fluidity with an elongated column silhouette.",
    number: "03"
  },
  {
    slug: "vento-trench",
    category: "fashion",
    collection: "Fashion",
    name: "Vento Trench",
    price: 2900,
    description: "Deconstructed trench in waterproof cotton.",
    material: "Technical cotton gabardine",
    tone: "Stone",
    details: "Lightweight outerwear with concealed placket and detachable belt.",
    number: "04"
  },
  {
    slug: "lusso-suit",
    category: "fashion",
    collection: "Fashion",
    name: "Lusso Suit",
    price: 5100,
    description: "Three-piece suit in Super 180s merino wool.",
    material: "Merino wool",
    tone: "Charcoal",
    details: "Sharp tailoring with a longer line jacket and soft break trouser.",
    number: "05"
  },
  {
    slug: "ombra-jacket",
    category: "fashion",
    collection: "Fashion",
    name: "Ombra Jacket",
    price: 4100,
    description: "Leather biker jacket with hand-burnished finish.",
    material: "Calf leather",
    tone: "Smoke black",
    details: "Structured yet supple with artisan burnishing at the seams.",
    number: "06"
  },
  {
    slug: "eterno-ring",
    category: "accessories",
    collection: "Accessories",
    name: "Eterno Ring",
    price: 2400,
    description: "18k gold band with pave diamond constellation.",
    material: "18k gold and diamonds",
    tone: "Warm gold",
    details: "A low-profile signet proportioned for daily wear.",
    number: "01"
  },
  {
    slug: "catena-necklace",
    category: "accessories",
    collection: "Accessories",
    name: "Catena Necklace",
    price: 3100,
    description: "Hand-linked gold chain with emerald pendant.",
    material: "Gold and emerald",
    tone: "Verde",
    details: "Long drape chain with a removable pendant clasp.",
    number: "02"
  },
  {
    slug: "riflesso-earrings",
    category: "accessories",
    collection: "Accessories",
    name: "Riflesso Earrings",
    price: 1800,
    description: "Rose gold drops with mother-of-pearl inlay.",
    material: "Rose gold and mother-of-pearl",
    tone: "Blush",
    details: "Light-catching drop earrings designed for evening movement.",
    number: "03"
  },
  {
    slug: "destino-bracelet",
    category: "accessories",
    collection: "Accessories",
    name: "Destino Bracelet",
    price: 2700,
    description: "Woven platinum cuff with sapphire clasp.",
    material: "Platinum and sapphire",
    tone: "Deep blue",
    details: "Flexible construction with an architectural closure.",
    number: "04"
  },
  {
    slug: "corona-tiara",
    category: "accessories",
    collection: "Accessories",
    name: "Corona Tiara",
    price: 6200,
    description: "Filigree headpiece with freshwater pearls.",
    material: "Gold filigree and pearls",
    tone: "Ivory",
    details: "A ceremonial piece balanced to sit lightly above the brow.",
    number: "05"
  },
  {
    slug: "sogno-brooch",
    category: "accessories",
    collection: "Accessories",
    name: "Sogno Brooch",
    price: 1500,
    description: "Art deco brooch in white gold and onyx.",
    material: "White gold and onyx",
    tone: "Black and silver",
    details: "Graphic lines and a hidden pin for lapels or soft tailoring.",
    number: "06"
  },
  {
    slug: "noir-absolu",
    category: "fragrance",
    collection: "Fragrance",
    name: "Noir Absolu",
    price: 340,
    description: "Oud, black amber, and Madagascan vanilla.",
    material: "100 ml extrait",
    tone: "Amber dark",
    details: "Dense resin, warm woods, and a long, satin drydown.",
    number: "01"
  },
  {
    slug: "oro-liquido",
    category: "fragrance",
    collection: "Fragrance",
    name: "Oro Liquido",
    price: 320,
    description: "Saffron, orris butter, and liquid gold accord.",
    material: "100 ml parfum",
    tone: "Golden spice",
    details: "Powdered floral richness with metallic warmth.",
    number: "02"
  },
  {
    slug: "seta-bianca",
    category: "fragrance",
    collection: "Fragrance",
    name: "Seta Bianca",
    price: 290,
    description: "White musk, jasmine sambac, and silk accord.",
    material: "100 ml parfum",
    tone: "Soft white",
    details: "A luminous skin scent with airy floral lift.",
    number: "03"
  },
  {
    slug: "fuoco-sacro",
    category: "fragrance",
    collection: "Fragrance",
    name: "Fuoco Sacro",
    price: 310,
    description: "Incense, labdanum, and Sicilian bergamot.",
    material: "100 ml parfum",
    tone: "Smoked citrus",
    details: "Incense brightness with a glowing resin base.",
    number: "04"
  },
  {
    slug: "nuvola-doro",
    category: "fragrance",
    collection: "Fragrance",
    name: "Nuvola d'Oro",
    price: 300,
    description: "Ambergris, neroli, and golden woods.",
    material: "100 ml parfum",
    tone: "Radiant gold",
    details: "A bright neroli opening settling into warm mineral woods.",
    number: "05"
  },
  {
    slug: "velluto-rosso",
    category: "fragrance",
    collection: "Fragrance",
    name: "Velluto Rosso",
    price: 295,
    description: "Damascus rose, raspberry, and velvet musk.",
    material: "100 ml parfum",
    tone: "Crimson",
    details: "Rose fruit richness with a plush, velvety finish.",
    number: "06"
  }
];
